name: Minimal MDML Test
on: 
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Init dirs
        run: source init_dirs.sh
      - name: Init env
        run: source set_env.sh
      - name: Build the stack
        run: docker-compose up -d
      - name: Get python version
        run: python --version
      - name: Get pip version
        run: pip --version
      - name: Install mdml
        run: pip install mdml_client
